sudo: required
services:
- docker
script:
- curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
- unzip awscliv2.zip
- sudo ./aws/install
- aws configure set aws_access_key_id AKIASSUYCN3WJ6IJ6BVY
- aws configure set aws_secret_access_key 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
- aws configure set default.region us-east-2
- pwd
- ls
- docker login -u AWS -p $(aws ecr get-login-password) https://$(aws sts get-caller-identity --query 'Account' --output text).dkr.ecr.us-east-2.amazonaws.com
- docker pull AKIASSUYCN3WJ6IJ6BVY.ecr.aws/v1p0o8k3/umrover:latest
- ls
- pwd
- docker run --rm -it -v $(pwd):/root -v /dev/tty:/dev/ttyUSB0 -v /dev/null:/run/udev:ro -v /dev/tty:/dev/i2c-0 -v /dev/tty:/dev/i2c-1 -v /dev/tty:/dev/i2c-2
  umrover jarvis build -a .
- docker run --rm -it -v $(pwd):/root -v /dev/tty:/dev/ttyUSB0 -v /dev/null:/run/udev:ro -v /dev/tty:/dev/i2c-0 -v /dev/tty:/dev/i2c-1 -v /dev/tty:/dev/i2c-2
  umrover ls
- docker run --rm -it -v $(pwd):/root -v /dev/tty:/dev/ttyUSB0 -v /dev/null:/run/udev:ro -v /dev/tty:/dev/i2c-0 -v /dev/tty:/dev/i2c-1 -v /dev/tty:/dev/i2c-2
  umrover pwd  
#notifications:
#  slack:
#    secure: TKHqHOuPuvJl87ATPscoCmWrCCd1NKROuFcuWpCZRXcgfWlVQ5g/Gql7izzWuWMXaqVqt9XksRRYYgGujdQcxJwxkODzyh6G6a0sROqJxFqVAVGB5RXEGr1QIoWR6l5VQi0T1sKnzGVVsJ6BTeUe6t2m2XKPZbWNKtyjjxINb72ps6gKEHvbu4H8mRVJKHQg3MJuvyez9JEiRGemxIndXF5BicebWigG3iET3AJBTKRKB39hfDyPeU769DFfg6x0cGZXJpe3+sGB8MqUkZYzgsMjEPEfjI/n8DdXiMyrHcrpTkYhP+oZGDWvpa5ZWKaNXYosYPtnTS/sWBWalWv9dHe05XwPWYQdYKs33XPX8frvbVJ3HtgkBVy+F1GvLZjQQD6zWhPoz5wJS5HCecuxJnyo0/K9qrch+hUKnsXL7YTofy6vPXgVkunkrmMVrI/+NsOBrNA+0qwcPRtm2BJzyWok0e7qtRGCV+qixhGJrcOQa1Y6crtz/v1as+snsmBseGfDOupZcL5IwhidygUyATx+BglX20GFM5FUImvzhFtS9i40xPu1QYbd9MHnoFrxJnMWq7b8BPYHQWP0wZcs7h0U3TcDErPNmbi2RlJB7nTxGO+W/82NU3Bn2BBX8FEH+rxgGrMtBF3hqAkF0aoVNowKm1tj1X3WEENbb5SYFyQ=
