sudo: required

before_install:
- sudo chmod u+x .travis/*.sh
- /bin/bash .travis/setup.sh

script:
 - pwd
 - curl https://umrovercontainer.s3.us-east-2.amazonaws.com/perceptionDev.zip --output perceptionDev.zip
 - pwd
 - unzip perceptionDev.zip
 - pwd
 - ls
 - pwd
 - singularity exec perceptionDev1.1.sif ls ../
 - singularity exec perceptionDev1.1.sif .././jarvis build -a .