
os: linux

language: go

go:
    - "1.15"

python:
    - "2.7"
    - "3.5"

addons:
  apt:
    packages:
      - flawfinder
      - squashfs-tools
      - uuid-dev
      - libuuid1
      - libffi-dev
      - libssl-dev
      - libssl1.0.0
      - libarchive-dev
      - libgpgme11-dev
      - libseccomp-dev
  homebrew:
   packages:
     - squashfs
   update: true


sudo: required
#dist: trusty


matrix:
  include:
    - python: "2.6"
    - python: "3.5"

before_install:
  - sudo chmod u+x .travis/*.sh
  - /bin/bash .travis/setup.sh

install:
  - true #Needed to prevent default install action "go get -t -v ./... whicih fails"

script:
 - pwd
 - curl https://umrovercontainer.s3.us-east-2.amazonaws.com/perceptionDev1.1.sif --output perceptionDev1.1.sif
 - pwd
 - ls
 - pwd
 - singularity exec perceptionDev1.1.sif ls ../
 - singularity exec perceptionDev1.1.sif ./jarvis build -a .