
os: linux

language: go

go:
    - "1.11"

python:
    - "2.7"
    - "3.5"

addons:
  apt:
    packages:
      - flawfinder
      - squashfs-tools
      - uuid-dev
      - libuuid1
      - libffi-dev
      - libssl-dev
      - libssl1.0.0
      - libarchive-dev
      - libgpgme11-dev
      - libseccomp-dev
  homebrew:
   packages:
     - squashfs
   update: true


sudo: required
#dist: trusty


matrix:
  include:
    - python: "2.6"
    - python: "3.5"

before_install:
  - sudo chmod u+x .travis/*.sh
  - /bin/bash .travis/setup.sh
  #- /bin/bash .travis/download.sh

install:
  - # override

script:
 #- singularity pull --name hello-world.simg shub://vsoch/hello-world
 #- singularity exec hello-world.simg ls /
 #- wget --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=10-CFtvKabLEEUe7j7kCCaL2_RQ53gOm3' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=10-CFtvKabLEEUe7j7kCCaL2_RQ53gOm3" -O perceptionDev.sif && rm -rf /tmp/cookies.txt
 - ls
 - singularity exec perceptionDev1.1.sif ls ../
 - singularity exec perceptionDev1.1.sif .././jarvis build -a .